spring:
  application:
    name: AuthServerExample
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgresDB
    username: ${user_postgres}
    password: ${pass_postgres}
    name: postgresDB
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==
  lifetime:
    access: 5
    refresh: 15
server:
  port: 8085
